# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='length',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat_mode',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.IntegerField(),
        ),
    ]
